Neo4j: make addAllDocumentsToNeo4j()
PathwayCommons/factoid pull request #1157
Opened 2023-03-30 20:40 UTC by lindajiawenli

#1156 

### Goal:

Create a function addAllDocumentsToNeo4j() that makes the appropriate nodes and edges in Neo4j for *ALL the documents in the "real" factoid database.

*with appropriate filters so that only public documents are used. Do not put demos, drafts, etc. into Neo4j.

2023-03-30 20:45 UTC, lindajiawenli commented
Current approach: using the `getDocuments` function found in `src/server/routes/api/document/index.js`, which seems appropriate for what I need to do (I want to get an array of document instances and call each of them with the previously made/tested `addDocumentToNeo4j`)

Running into a bug: 
`Error: Expected at least one of 'cache', 'factory', 'factoryOptions' to be defined`

2023-03-31 18:52 UTC, lindajiawenli commented
After running `node -r esm src/neo4j/add-all-docs.js` and then opening `http://localhost:7474/browser/` (this is Neo4j Browser, from a docker container), run `MATCH (n) RETURN n` in the command line and this is what you will see:

![Screen Shot 2023-03-31 at 2 41 34 PM](https://user-images.githubusercontent.com/66929920/229205290-4e9f4b28-2621-438c-809f-d773b1c6dd3a.png)

2023-04-03 15:05 UTC, jvwong requested changes

2023-04-03 15:05 UTC, jvwong commented on src/neo4j/neo4j-document.js
> +  let testDb;
Here's where we need to have a configurable database instance that could access  non-test (production) data.

 In practice, probably need to hook into those used by a running factoid server instance: `db` in `src/server/db.js` which uses environment variables in `src/config.js` which could be overwritten at runtime.

2023-04-03 15:10 UTC, jvwong commented
One caveat:  if you use any existing functions that touch the database (e.g. `get Documents` in `src/server/routes/api/document/index.js`) it uses the database settings defined on the factoid server 

https://github.com/PathwayCommons/factoid/blob/906ce07f089578f35c20e6a627e61bc70ee9bea2/src/config.js#L51-L57

2023-04-03 15:20 UTC, jvwong commented
I'm starting to reconsider the necessity of this at all: If `addAllDocumentsToNeo4j` is just a for loop around `addDocumentToNeo4j`, what benefit does it provide with respect to the use case(s)?

2023-04-03 16:04 UTC, lindajiawenli commented on src/neo4j/neo4j-document.js
> +    const { total, results } = await getDocuments(opts);
Yeah, I did notice that, and I would've liked to get Document instances directly, but I wasn't quite sure how to do that and `getDocuments` seemed too convenient for me to not use.

Is there a function that does that and I simply missed it, or would I have to make one?

2023-04-03 16:26 UTC, jvwong commented
Let's close and I'll follow up on #1157- probably reuse this code there.

2023-04-03 16:26 UTC, closed without merging